### ISSUE TITLE
Compare annotations from multiple collaborators relating to a single image

### ISSUE THREAD

**Issue by ChasNelson1990** [gliff-ai/roadmap#3]
Add some way to view two annotations either on the same image (useful for segmentation) and/or side-by-side (maybe more useful for lots of splines).

**Comment by joshuajames-smith** [comment]
The UI/UX design of this feature is spilt into two issues between our **CURATE** repo and our **ANNOTATE** repo:

- [ ] https://github.com/gliff-ai/curate/issues/349
- [ ] https://github.com/gliff-ai/annotate/issues/674
