### ISSUE TITLE
Platform Walkthrough > Intercom

### ISSUE THREAD

**Issue by joshuajames-smith** [gliff-ai/roadmap#81]
## Problem

Users who are new to the platform are very much likely to experience confusion as they are unfamiliar with the UI and UX we have built our platform upon. This will cause issues onboarding and create a negative UX. 

## Solution

Use Intercom to create a product tour of the platform which goes over the main points. This is going to be different for all 3 user types? - team owners, team members and collaborators. 

## Considered Alternatives

Use the `Help` button which is being implemented in issue https://github.com/gliff-ai/dominate/issues/306 to offer to replay the tour. In the future, we could expand this from general tour walkthrough to platform specific or even task/feature specific.

![IMG_0753](https://user-images.githubusercontent.com/83074763/163419627-6c86971c-a99f-4288-8987-d8f36d8c99a5.jpg)

## Additional Context

Adobe Fresco has a great example of a quick walkthrough tour which we should take UX inspiration from.

<img width="400" alt="IMG_0752" src="https://user-images.githubusercontent.com/83074763/163418604-8d6b45fd-42fc-4fd5-9fd7-e200a04eee45.jpg"> <img width="400" alt="IMG_0741" src="https://user-images.githubusercontent.com/83074763/163418616-57bbbf51-3b88-4d9e-8b40-e08edd66986a.jpg">
<img width="400" alt="IMG_0742" src="https://user-images.githubusercontent.com/83074763/163418624-55a6de64-7bc1-4398-a565-55c99ea3230c.jpg"> <img width="400" alt="IMG_0743" src="https://user-images.githubusercontent.com/83074763/163418627-51483f52-ae5e-4440-a0cb-20e4d6f9071a.jpg">

**Comment by cooper667** [comment]
I've installed Intercom on Staging (https://github.com/gliff-ai/dominate/pull/633) and created a very quick (and bad) product tour.

I think the best way to manage this is have several tours, one for main Dominate (which is basically Manage), then one when they hit Curate and Annotate. Each can lead into the other with "Create a Project" or "Upload an Image" etc.

@joshuajames-smith Create them here, set them live and they will show on Staging for now, until Intercom is merged live https://app.intercom.com/a/apps/fhkh0l1p/outbound/tour 

You should be able to segment the tours by user level too (their access level is set as a custom attribute on a user profile)

**Comment by ChasNelson1990** [comment]
Marking as closed as the tech side is done.
